use_frameworks!
platform :ios, '13.0'

target 'JKCommunity_Example' do
  pod 'JKCommunity', :path => '../'
  pod 'JKFirebaseSDK', :git => 'https://github.com/monibu1548/JKFirebaseSDK'

  target 'JKCommunity_Tests' do
    inherit! :search_paths

  end
end
